services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=mongo:27017
      - PORT=8080
      - CONTRACT_ADDRESS=0xcdF367bb783bC7C3681df313364fdf9b1E82A7aD
  mongo:
    image: mongo:latest

